[env]
FOO = "bar"
[window]
dimensions = { columns = 100, lines = 50 }
padding = { x = 20, y = 20 }
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"
[font]
normal = { family = "0xProto Nerd Font", style = "regular" }
size = 22 
[colors]
primary = { foreground = "#d8d8d8", background = "#241D3B" }
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
transparent_background_colors = true
draw_bold_text_with_bright_colors = true
[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }
thickness = 0.5
[mouse]
hide_when_typing = true
[keyboard]
bindings = [
    { key = "W", mods = "Control|Shift", action = "Quit" },
]
